# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a38aab5d77f923e49cd8919b4c608b64a6c0b1d0c41d606f661d3b24c6c2a64a327652909c246ad20f2c5ba372f4e0b2724dfce07a13f68d55750ac48f3691c3

test:
  secret_key_base: 96b8adf32f80fc3d4f70cac03ffaa6091d1b9a55ed2d86881134566cc3097d61fab5c9ea7481ea17060c984a46f03254e68c7d87f919cdb741a9d2bf01694d75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
